
services:

  database:
    image: postgres:16-alpine
    container_name: kanban-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban_secret
      POSTGRES_DB: kanban
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - reseauproj
  
  backend:
    image: loueslati/projet-docker-backend
    container_name: kanban-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - reseauproj

  frontend:
    image: linaesther/projet-docker-frontend
    container_name: kanban-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - reseauproj

volumes:
  postgresdata:

networks:
  reseauproj:
    driver: bridge